inventory = ["Laptop", "Mouse","Keyboard"]
print(inventory)
inventory.append("Monitor")
print(inventory)
inventory.insert(1,"Printer")
print("the updated inventory list is:",inventory)
new_products=["Scanner","Webcam"]
inventory.extend(new_products)
print("the updated inventory list is:",inventory)
inventory.remove("Mouse")
print("the updated inventory list is:",inventory)
shipped_product=inventory.pop(2)
print("shiped product is:",shipped_product)
print("the updated inventory list is:",inventory)

print("Laptop appear")
inventory.count("Laptop")
print("Monitor is at index:",inventory.index("Monitor"))
inventory.sort()
print("Sorted inventory list is:",inventory)
inventory.reverse()
print("Reversed inventory list is:",inventory)
backup=inventory.copy()
print("Backup inventory list is:",backup)
temp_inventory=backup.copy()
temp_inventory.clear()
print("Temporary inventory list is:",temp_inventory)
clear: temp_inventory.clear()
